_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 84
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.7
            "6": 4.46.3
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
bf16:
    value: true
dtype:
    value: null
fp16:
    value: false
gradient_accumulation_steps:
    value: 2
learning_rate:
    value: 0.0002
load_in_4bit:
    value: true
lr_scheduler_type:
    value: cosine
max_seq_length:
    value: 2048
max_steps:
    value: 60
model_name:
    value: unsloth/Llama-3.2-3B-bnb-4bit
optim:
    value: adamw_8bit
output_dir:
    value: outputs
per_device_train_batch_size:
    value: 128
seed:
    value: 3407
warmup_steps:
    value: 5
weight_decay:
    value: 0.01
